// This file was auto generated by build.gradle.kts
package meetnote3.static

const val FRONTEND_HTML = """
<!doctype html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Meetnote3</title>
</head>
<body>
<div id="root">Hello World</div>
<script src="frontend.js"></script>
</body>
</html>

"""
