// This file was auto generated by build.gradle.kts
package meetnote3.static

const val FRONTEND_CSS = """
.row {
    display: grid;
    grid-template-columns: 30% 70%;
    gap: 10px;
    padding: 5px;
}

@media (max-width: 800px) {
    .row {
        grid-template-columns: 1fr;
    }
}

ul {
    padding-left: 0;
    list-style: none;
}

"""
