import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("multiplatform") version "2.0.0"
    kotlin("plugin.power-assert") version "2.0.0"
    kotlin("plugin.serialization") version "2.0.0"
    id("io.gitlab.arturbosch.detekt")
    id("org.jlleitschuh.gradle.ktlint")
}

kotlin {
    macosArm64("native") {
        binaries {
            executable()
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation(project.dependencies.platform("io.ktor:ktor-bom:2.3.12"))
                implementation("io.ktor:ktor-client-core")
                implementation("io.ktor:ktor-client-darwin")
                implementation("io.ktor:ktor-server-core")
                implementation("io.ktor:ktor-server-cio")
                implementation("io.ktor:ktor-server-content-negotiation")
                implementation("io.ktor:ktor-serialization-kotlinx-json")

                implementation("com.squareup.okio:okio:3.9.0")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1")
                implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.6.0")
                implementation("org.jetbrains.kotlinx:kotlinx-html:0.11.0")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.0")
            }
        }
    }
}

// ./gradlew :capjoy:runDebug -PexecArgs="displays"
tasks.register<Exec>("runDebug") {
    dependsOn("linkDebugExecutableNative")
    val arguments = project.findProperty("execArgs")?.toString()?.split(" ") ?: listOf()
    args(arguments)
    environment("CAPJOY_GRADLE_RUN_DEBUG", "true")
    executable = file("$buildDir/bin/native/debugExecutable/meetnote3.kexe").absolutePath
    standardInput = System.`in`
}

tasks.register("generateGpt2Kt") {
    doLast {
        val sourceFile = file("src/commonMain/resources/summarize-gpt2.py")
        val targetFile = file("src/nativeMain/kotlin/meetnote3/python/Gpt2.kt")
        val content = sourceFile.readText()

        val kotlinFileContent = listOf(
            "// This file was auto generated by build.gradle.kts",
            "package meetnote3.python\n",
            "const val SUMMARIZE_GPT2 = \"\"\"",
            content,
            "\"\"\"\n",
        ).joinToString("\n")

        targetFile.parentFile.mkdirs()
        targetFile.writeText(kotlinFileContent)
    }
}

tasks.register("generateFrontendJs") {
    doLast {
        val sourceFile = file("src/commonMain/resources/frontend.js")
        val targetFile = file("src/nativeMain/kotlin/meetnote3/static/FrontendJs.kt")
        val content = sourceFile.readText()

        val kotlinFileContent = listOf(
            "// This file was auto generated by build.gradle.kts",
            "package meetnote3.static\n",
            "const val FRONTEND_JS = \"\"\"",
            content,
            "\"\"\"\n",
        ).joinToString("\n")

        targetFile.parentFile.mkdirs()
        targetFile.writeText(kotlinFileContent)
    }
}

tasks.register("generateFrontendHtml") {
    doLast {
        val sourceFile = file("src/commonMain/resources/frontend.html")
        val targetFile = file("src/nativeMain/kotlin/meetnote3/static/FrontendHtml.kt")
        val content = sourceFile.readText()

        val kotlinFileContent = listOf(
            "// This file was auto generated by build.gradle.kts",
            "package meetnote3.static\n",
            "const val FRONTEND_HTML = \"\"\"",
            content,
            "\"\"\"\n",
        ).joinToString("\n")

        targetFile.parentFile.mkdirs()
        targetFile.writeText(kotlinFileContent)
    }
}

tasks.register("generateFrontendCss") {
    doLast {
        val sourceFile = file("src/commonMain/resources/frontend.css")
        val targetFile = file("src/nativeMain/kotlin/meetnote3/static/FrontendCss.kt")
        val content = sourceFile.readText()

        val kotlinFileContent = listOf(
            "// This file was auto generated by build.gradle.kts",
            "package meetnote3.static\n",
            "const val FRONTEND_CSS = \"\"\"",
            content,
            "\"\"\"\n",
        ).joinToString("\n")

        targetFile.parentFile.mkdirs()
        targetFile.writeText(kotlinFileContent)
    }
}

tasks.withType<KotlinCompile> {
    dependsOn("generateGpt2Kt")
    dependsOn("generateFrontendJs")
    dependsOn("generateFrontendHtml")
    dependsOn("generateFrontendCss")
}
